### Site Settings ###
title               : Dimitris Liapis
description         : >-
                      Senior Software Engineer
baseurl             : ""            # Empty quotes for username.github.io direct hosting
repository          : dliapis/dliapis.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/**                                    # Exclude all documentation
  - blog/**                                             # Exclude all blog posts
  - _posts/**                                           # Exclude all blog posts directory


### Author Info ###
author:
  name              : Dimitris Liapis
  image             : https://i.imgur.com/uyDNQnn.jpg
# behance           : your_username
# dribbble          : your_username
  email             : liapis.di@outlook.com
# facebook          : your_username
  github            : dliapis
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : liapisdimitrios
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - _posts/**                                           # Exclude all blog posts
  - blog/**                                             # Exclude blog directory
